apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingms
  template:
    metadata:
      labels:
        app: bookingms
    spec:
      containers:
      - name: bookingms-container
        image: docker.io/nitishbits/bookingms-i:latest
        ports:
        - containerPort: 3002
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bookingms-service
spec:
  selector:
    app: bookingms
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: NodePort
  selector:
    app: bookingms
