apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingdb
  template:
    metadata:
      labels:
        app: bookingdb
    spec:
      containers:
      - name: bookingdb-c
        image: docker.io/nitishbits/bookingdb-i:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bookingdb-service
spec:
  selector:
    app: bookingdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
